const companyNames = [
    "ACCENTURE",
    "ACCOLITE",
    "AMAZON",
    "AMERICAN EXPRESS",
    "APPIAN",
    "APPLE",
    "APTIV",
    "ARCADIA",
    "ATHENAHEALTH",
    "BANK OF AMERICA",
    "BARCLAYS",
    "BLUE YONDER",
    "BNY",
    "CATERPILLAR",
    "CHRONUS",
    "CITI",
    "CODESTAX.AI",
    "COMPLYANCE",
    "CONGRUENT",
    "D. E. SHAW",
    "DOVER",
    "EUCLOID DATA SOLUTIONS",
    "FEDEX",
    "FIDELITY",
    "FORD",
    "GAVS",
    "GIGAMON",
    "ICANIO TECHNOLOGIES",
    "IDFC FIRST BANK",
    "INFINERA",
    "J K FENNER",
    "JOHN DEERE",
    "KLA",
    "LARSEN & TURBO",
    "LATENTVIEW",
    "LISTER TECHNOLOGIES",
    "LOGITECH",
    "MINDGATE",
    "MORGAN STANLEY",
    "NCR VOYIX",
    "NORTONLIFELOCK",
    "OPTUM",
    "ORACLE",
    "RAMCO SYSTEMS",
    "RANDOMWALK.AI",
    "SAGENT",
    "SAP LABS",
    "SEARCE",
    "SECUREW2",
    "SOCIETE GENERALE",
    "STANDARD CHARTERED GBS",
    "STARTENS SYSTEM",
    "TATA DIGITAL",
    "TCS",
    "TEJAS NETWORKS",
    "TEKION",
    "TRIMBLE",
    "VEGROW",
    "VERIZON",
    "VIASAT",
    "VISA",
    "VIVRITI CAPITAL",
    "VOLVO",
    "WALMART",
    "WELLS FARGO",
    "ZOOMRX"
  ];

  
  modules.export = companyNames;